name: Trigger library build & release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@main
      
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with: 
          node-version: '14.x'
          
      - uses: jgierer12/npm-auth-gpr@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Add token to .npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${AUTH_TOKEN}" >> .npmrc
        env:  
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install node modules, build & release
        run: |
          npm install
          npm run build
          npx release-it minor --ci
